# Generated by Django 5.1.2 on 2024-11-05 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_customer_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='verified_type',
            field=models.CharField(choices=[(' verified', ' verified'), ('unverified', 'unverified'), ('most viewed', 'most viewed')], default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(blank=True, choices=[('one time', 'one time'), ('Recurring', 'Recurring')], max_length=10, null=True),
        ),
    ]
