# Generated by Django 5.1.2 on 2024-11-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_customer_verified_type_alter_plan_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.status'),
            preserve_default=False,
        ),
    ]
