# Generated by Django 5.1.2 on 2024-11-05 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_status_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Status',
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.status'),
            preserve_default=False,
        ),
    ]
