# Generated by Django 5.1.2 on 2024-11-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_customer_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
