# Generated by Django 5.1.2 on 2024-11-05 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_remove_plan_features_alter_plan_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='features',
        ),
    ]
