# Generated by Django 5.1.2 on 2024-11-08 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_blocked_customer_blocked_features_blocked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_no',
        ),
        migrations.AddField(
            model_name='order',
            name='transaction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.transaction'),
            preserve_default=False,
        ),
    ]
